#!/bin/bash

echo "IRRLICHT CONFIGURE"

libdir="/lib"
prefix=""

for p in "$@"; do
	case $p in
		--prefix=*)
		prefix="${p#*=}"
		shift
		;;
		--libdir=*)
		libdir="${p#*=}"
		shift
		;;
	esac
done

cat <<EOF >> Makefile
all:
	\$(MAKE) -C source/Irrlicht
install:
	mkdir -p $prefix/$libdir
	cp lib/Linux/libIrrlicht.a $prefix/$libdir
	mkdir -p $prefix/include/irrlicht
	cp -R include/* $prefix/include/irrlicht/
EOF
