#!/bin/bash

libdir="/lib"
prefix=""

for p in "$@"; do
	case $p in
		--prefix=*)
		prefix="${p#*=}"
		shift
		;;
		--libdir=*)
		libdir="${p#*=}"
		shift
		;;
	esac
done

cmake \
	-DIRRLICHT_LIBRARY=$prefix/$libdir/libIrrlicht.a -DIRRLICHT_INCLUDE_DIR=$prefix/include/irrlicht \
	-DENABLE_CURSES=0 \
	-DCMAKE_INSTALL_PREFIX=$prefix \
	-DLUA_INCLUDE_DIR=$prefix/include/luajit-2.0 \
	.
